[features]
seeds = false

[programs.localnet]
lab_lunch_dao = "HtZAJbfvjxWGgMSQh9Aht28sPNX1EC5jsGoeoq9DDqkA"

[programs.devnet]
lab_lunch_dao = "HtZAJbfvjxWGgMSQh9Aht28sPNX1EC5jsGoeoq9DDqkA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/yasushi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --resolveJsonModule"
